# Generated by Django 5.2.1 on 2026-02-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_alter_subscriber_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
