# Generated by Django 5.2.1 on 2026-02-27 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_alter_subscriber_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscription_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
