# Generated by Django 5.2.1 on 2026-02-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.CharField(choices=[('1m', '1 Month'), ('2m', '2 Months'), ('3m', '3 Months'), ('6m', '6 Months'), ('1y', '1 Year')], max_length=5),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='quantity',
            field=models.CharField(choices=[('250ml', '250 ML'), ('500ml', '500 ML'), ('750ml', '750 ML'), ('1l', '1 Litre'), ('2l', '2 Litre')], max_length=10),
        ),
    ]
