# Generated by Django 5.2.11 on 2026-03-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0004_alter_subscriber_subscription_date"),
        ("order", "0002_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="subscriber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_orders",
                to="subscribers.subscriber",
            ),
        ),
    ]
